"""Versioned provider-ownership governance for the ATLAS FMP-first migration.

This module is metadata only.  It deliberately contains no provider clients,
network calls, environment access, provider-selection logic, or runtime hooks.
Consumers must not use this registry to select or merge provider values until a
separately reviewed migration phase changes the owning acquisition path.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Final


PROVIDER_OWNERSHIP_VERSION: Final = "PROVIDER_OWNERSHIP_V1"

CURRENT_PRIMARY: Final = "CURRENT_PRIMARY"
MIGRATION_VALIDATION: Final = "MIGRATION_VALIDATION"
SHADOW_VALIDATION: Final = "SHADOW_VALIDATION"
READY_FOR_CUTOVER: Final = "READY_FOR_CUTOVER"
FMP_PRIMARY_YAHOO_FALLBACK: Final = "FMP_PRIMARY_YAHOO_FALLBACK"
FMP_PRIMARY: Final = "FMP_PRIMARY"
LEGACY_PENDING_REMOVAL: Final = "LEGACY_PENDING_REMOVAL"

SUPPORTED_AUTHORITY_STATES: Final = frozenset({
    CURRENT_PRIMARY,
    MIGRATION_VALIDATION,
    SHADOW_VALIDATION,
    READY_FOR_CUTOVER,
    FMP_PRIMARY_YAHOO_FALLBACK,
    FMP_PRIMARY,
    LEGACY_PENDING_REMOVAL,
})

FMP: Final = "FMP"
YAHOO: Final = "YAHOO"
FINNHUB: Final = "FINNHUB"
NEWSAPI: Final = "NEWSAPI"
SEC: Final = "SEC"
ATLAS: Final = "ATLAS"
LICENSED_MARKET_DATA_PROVIDER: Final = "LICENSED_MARKET_DATA_PROVIDER"
MIXED_LEGACY: Final = "MIXED_LEGACY"

SUPPORTED_PROVIDERS: Final = frozenset({
    FMP,
    YAHOO,
    FINNHUB,
    NEWSAPI,
    SEC,
    ATLAS,
    LICENSED_MARKET_DATA_PROVIDER,
    MIXED_LEGACY,
})

COMMERCIAL_LICENSE_PENDING: Final = "COMMERCIAL_LICENSE_PENDING"
PUBLIC_FILING_SOURCE: Final = "PUBLIC_FILING_SOURCE"
ATLAS_PROPRIETARY: Final = "ATLAS_PROPRIETARY"
LICENSE_REQUIRED: Final = "LICENSE_REQUIRED"


@dataclass(frozen=True)
class ProviderOwnership:
    family: str
    intended_primary: str
    current_primary: str
    fallbacks: tuple[str, ...]
    authority_status: str
    commercial_status: str
    canonical_schema: str
    cache_ttl_seconds: int | None
    consumers: tuple[str, ...]
    methodology_effect: str
    rollback_owner: str


@dataclass(frozen=True)
class ExplicitResearchAuthority:
    """FIRST.3 governance declaration; acquisition code does not consult it."""

    family: str
    primary: str
    rollback_owner: str
    authority_status: str
    commercial_status: str


def _entry(
    family: str,
    intended_primary: str,
    current_primary: str,
    fallbacks: tuple[str, ...],
    authority_status: str,
    commercial_status: str,
    canonical_schema: str,
    cache_ttl_seconds: int | None,
    consumers: tuple[str, ...],
    methodology_effect: str,
    rollback_owner: str,
) -> ProviderOwnership:
    return ProviderOwnership(
        family=family,
        intended_primary=intended_primary,
        current_primary=current_primary,
        fallbacks=fallbacks,
        authority_status=authority_status,
        commercial_status=commercial_status,
        canonical_schema=canonical_schema,
        cache_ttl_seconds=cache_ttl_seconds,
        consumers=consumers,
        methodology_effect=methodology_effect,
        rollback_owner=rollback_owner,
    )


RESEARCH = ("SCANNER_ENRICHMENT", "RESEARCH", "ASK_ATLAS")
RESEARCH_HOME = ("SCANNER_ENRICHMENT", "RESEARCH", "ASK_ATLAS", "HOME")

# The tuple is intentionally immutable and declarative.  FIRST.1 does not
# import it from any runtime consumer and does not change current authority.
PROVIDER_OWNERSHIP: Final[tuple[ProviderOwnership, ...]] = (
    _entry("COMPANY_PROFILE_REFERENCE", FMP, YAHOO, (FMP,), SHADOW_VALIDATION, COMMERCIAL_LICENSE_PENDING, "COMPANY_PROFILE_V1", 604800, RESEARCH_HOME, "INPUT_ONLY_EXISTING_METHOD", YAHOO),
    _entry("COMPANY_CLASSIFICATION", FMP, YAHOO, (FMP,), SHADOW_VALIDATION, COMMERCIAL_LICENSE_PENDING, "COMPANY_CLASSIFICATION_V1", 604800, ("UNIVERSE", "SCANNER", "RESEARCH", "ETF_RESEARCH"), "EXCLUSION_AND_ROUTING_INPUT", YAHOO),
    _entry("MARKET_CAPITALIZATION", FMP, YAHOO, (FMP,), SHADOW_VALIDATION, COMMERCIAL_LICENSE_PENDING, "MARKET_CAPITALIZATION_V1", 14400, ("SCANNER", "RESEARCH", "HOME"), "ELIGIBILITY_INPUT", YAHOO),
    _entry("FINANCIAL_STATEMENTS", FMP, MIXED_LEGACY, (YAHOO,), MIGRATION_VALIDATION, COMMERCIAL_LICENSE_PENDING, "FINANCIAL_STATEMENTS_V1", 28800, RESEARCH, "INPUT_ONLY_EXISTING_METHOD", YAHOO),
    _entry("KEY_METRICS", FMP, MIXED_LEGACY, (YAHOO,), MIGRATION_VALIDATION, COMMERCIAL_LICENSE_PENDING, "KEY_METRICS_V1", 28800, RESEARCH, "INPUT_ONLY_EXISTING_METHOD", YAHOO),
    _entry("FINANCIAL_RATIOS", FMP, MIXED_LEGACY, (YAHOO,), MIGRATION_VALIDATION, COMMERCIAL_LICENSE_PENDING, "FINANCIAL_RATIOS_V1", 28800, RESEARCH, "INPUT_ONLY_EXISTING_METHOD", YAHOO),
    _entry("FINANCIAL_GROWTH", FMP, YAHOO, (FMP,), SHADOW_VALIDATION, COMMERCIAL_LICENSE_PENDING, "FINANCIAL_GROWTH_V1", 28800, ("SCANNER", "RESEARCH", "VALUATION"), "SCORING_AND_VALUATION_INPUT", YAHOO),
    _entry("REVENUE_SEGMENTATION", FMP, MIXED_LEGACY, (), MIGRATION_VALIDATION, COMMERCIAL_LICENSE_PENDING, "REVENUE_SEGMENTATION_V1", 28800, ("RESEARCH", "ASK_ATLAS"), "RESEARCH_ONLY", MIXED_LEGACY),
    _entry("COMPANY_PEERS", FMP, FMP, (), FMP_PRIMARY, COMMERCIAL_LICENSE_PENDING, "COMPANY_PEERS_V1", 604800, RESEARCH, "RESEARCH_ONLY", FMP),
    _entry("EARNINGS_HISTORY", FMP, MIXED_LEGACY, (YAHOO,), MIGRATION_VALIDATION, COMMERCIAL_LICENSE_PENDING, "EARNINGS_HISTORY_V1", 28800, ("SCANNER_ENRICHMENT", "RESEARCH", "EARNINGS", "ASK_ATLAS"), "DETERMINISTIC_CLASSIFICATION_INPUT", YAHOO),
    _entry("EARNINGS_ACTUAL_VS_ESTIMATE", FMP, MIXED_LEGACY, (YAHOO,), MIGRATION_VALIDATION, COMMERCIAL_LICENSE_PENDING, "EARNINGS_COMPARISON_V1", 28800, ("RESEARCH", "EARNINGS", "ASK_ATLAS"), "DETERMINISTIC_CLASSIFICATION_INPUT", YAHOO),
    _entry("ANALYST_ESTIMATES", FMP, MIXED_LEGACY, (YAHOO, FINNHUB), SHADOW_VALIDATION, COMMERCIAL_LICENSE_PENDING, "ANALYST_ESTIMATES_V1", 14400, RESEARCH, "INPUT_ONLY_EXISTING_METHOD", YAHOO),
    _entry("ANALYST_CONSENSUS", FMP, FINNHUB, (FMP, YAHOO), SHADOW_VALIDATION, COMMERCIAL_LICENSE_PENDING, "ANALYST_CONSENSUS_V1", 14400, RESEARCH, "INPUT_ONLY_EXISTING_METHOD", FINNHUB),
    _entry("ANALYST_PRICE_TARGETS", FMP, FINNHUB, (FMP, YAHOO), SHADOW_VALIDATION, COMMERCIAL_LICENSE_PENDING, "ANALYST_PRICE_TARGETS_V1", 14400, RESEARCH_HOME, "DECISION_TARGET_INPUT_EXISTING_METHOD", FINNHUB),
    _entry("ANALYST_FIRM_ACTIONS", FMP, FINNHUB, (FMP, YAHOO), SHADOW_VALIDATION, COMMERCIAL_LICENSE_PENDING, "ANALYST_ACTION_V1", 14400, RESEARCH, "RESEARCH_ONLY", FINNHUB),
    _entry("INSTITUTIONAL_OWNERSHIP", FMP, YAHOO, (FMP,), SHADOW_VALIDATION, COMMERCIAL_LICENSE_PENDING, "INSTITUTIONAL_OWNERSHIP_V1", 43200, RESEARCH, "RESEARCH_ONLY", YAHOO),
    _entry("FUND_13F_HOLDINGS", FMP, MIXED_LEGACY, (FMP,), SHADOW_VALIDATION, COMMERCIAL_LICENSE_PENDING, "FUND_13F_HOLDINGS_V1", 86400, RESEARCH, "RESEARCH_ONLY", MIXED_LEGACY),
    _entry("INSIDER_ACTIVITY", FMP, FINNHUB, (), MIGRATION_VALIDATION, COMMERCIAL_LICENSE_PENDING, "INSIDER_ACTIVITY_V1", 43200, RESEARCH, "RESEARCH_ONLY", FINNHUB),
    _entry("COMPANY_NEWS", FMP, NEWSAPI, (FMP, FINNHUB, YAHOO), SHADOW_VALIDATION, COMMERCIAL_LICENSE_PENDING, "COMPANY_NEWS_V1", 3600, RESEARCH_HOME, "RESEARCH_ONLY", NEWSAPI),
    _entry("PRESS_RELEASES", FMP, MIXED_LEGACY, (FMP,), SHADOW_VALIDATION, COMMERCIAL_LICENSE_PENDING, "PRESS_RELEASES_V1", 3600, RESEARCH, "RESEARCH_ONLY", MIXED_LEGACY),
    _entry("TRANSCRIPT_INDEX", FMP, MIXED_LEGACY, (FMP,), MIGRATION_VALIDATION, COMMERCIAL_LICENSE_PENDING, "TRANSCRIPT_INDEX_V1", 86400, ("RESEARCH", "EARNINGS", "ASK_ATLAS"), "RESEARCH_ONLY_INACTIVE", MIXED_LEGACY),
    _entry("TRANSCRIPT_CONTENT", FMP, MIXED_LEGACY, (FMP,), MIGRATION_VALIDATION, COMMERCIAL_LICENSE_PENDING, "TRANSCRIPT_INTELLIGENCE_V1", None, ("RESEARCH", "EARNINGS", "ASK_ATLAS"), "RESEARCH_ONLY_INACTIVE", MIXED_LEGACY),
    _entry("ETF_PROFILE", FMP, YAHOO, (FMP,), SHADOW_VALIDATION, COMMERCIAL_LICENSE_PENDING, "ETF_PROFILE_V1", 86400, ("SCANNER", "ETF_RESEARCH", "RESEARCH"), "ETF_ROUTING_AND_RESEARCH", YAHOO),
    _entry("ETF_HOLDINGS", FMP, YAHOO, (FMP,), MIGRATION_VALIDATION, COMMERCIAL_LICENSE_PENDING, "ETF_HOLDINGS_V1", 86400, ("ETF_RESEARCH", "RESEARCH"), "RESEARCH_ONLY", YAHOO),
    _entry("ETF_ALLOCATIONS", FMP, YAHOO, (FMP,), MIGRATION_VALIDATION, COMMERCIAL_LICENSE_PENDING, "ETF_ALLOCATIONS_V1", 86400, ("ETF_RESEARCH", "RESEARCH"), "RESEARCH_ONLY", YAHOO),
    _entry("MARKET_ECONOMIC_CONTEXT", FMP, MIXED_LEGACY, (), MIGRATION_VALIDATION, COMMERCIAL_LICENSE_PENDING, "MARKET_ECONOMIC_CONTEXT_V1", 3600, ("HOME", "RESEARCH", "ASK_ATLAS"), "EXPLANATORY_ONLY", MIXED_LEGACY),
    _entry("SEC_FILINGS", SEC, SEC, (FMP,), CURRENT_PRIMARY, PUBLIC_FILING_SOURCE, "SEC_FILINGS_V1", 21600, ("RESEARCH", "POLICY_INTELLIGENCE", "ASK_ATLAS"), "RESEARCH_ONLY", SEC),
    _entry("HISTORICAL_DAILY_OHLCV", LICENSED_MARKET_DATA_PROVIDER, YAHOO, (FMP,), MIGRATION_VALIDATION, LICENSE_REQUIRED, "DAILY_OHLCV_V1", 1800, ("SCANNER", "RESEARCH", "TECHNICAL_INTELLIGENCE"), "TECHNICAL_INPUT_EXISTING_METHOD", YAHOO),
    _entry("LIVE_QUOTES_TRADES", LICENSED_MARKET_DATA_PROVIDER, YAHOO, (), LEGACY_PENDING_REMOVAL, LICENSE_REQUIRED, "LIVE_MARKET_EVENT_V1", 120, ("HOME", "WATCHLIST", "PORTFOLIO"), "PRESENTATION_ONLY_CURRENTLY", YAHOO),
    _entry("WEBSOCKET_MARKET_FEED", LICENSED_MARKET_DATA_PROVIDER, LICENSED_MARKET_DATA_PROVIDER, (), CURRENT_PRIMARY, LICENSE_REQUIRED, "LIVE_MARKET_EVENT_V1", None, ("LIVE_MARKET_GATEWAY",), "INFRASTRUCTURE_ONLY_INACTIVE", LICENSED_MARKET_DATA_PROVIDER),
    _entry("INTRADAY_MARKET_DATA", LICENSED_MARKET_DATA_PROVIDER, YAHOO, (), LEGACY_PENDING_REMOVAL, LICENSE_REQUIRED, "INTRADAY_OHLCV_V1", 120, ("HOME", "WATCHLIST", "RESEARCH"), "PRESENTATION_ONLY_CURRENTLY", YAHOO),
    _entry("REAL_TIME_ALERTS", LICENSED_MARKET_DATA_PROVIDER, LICENSED_MARKET_DATA_PROVIDER, (), CURRENT_PRIMARY, LICENSE_REQUIRED, "CUSTOMER_ALERT_EVENT_V1", None, ("LIVE_MARKET_ALERTS",), "INFRASTRUCTURE_ONLY_INACTIVE", LICENSED_MARKET_DATA_PROVIDER),
    _entry("LIVE_BULL_RUN_RADAR_INPUT", LICENSED_MARKET_DATA_PROVIDER, LICENSED_MARKET_DATA_PROVIDER, (), CURRENT_PRIMARY, LICENSE_REQUIRED, "DAILY_BAR", None, ("TECHNICAL_INTELLIGENCE",), "PROVISIONAL_INACTIVE", LICENSED_MARKET_DATA_PROVIDER),
    _entry("TECHNICAL_CALCULATIONS", ATLAS, ATLAS, (), CURRENT_PRIMARY, ATLAS_PROPRIETARY, "ATLAS_TECHNICALS_V1", None, ("SCANNER", "RESEARCH", "BULL_RUN_RADAR"), "METHODOLOGY_OWNER", ATLAS),
    _entry("OPPORTUNITY", ATLAS, ATLAS, (), CURRENT_PRIMARY, ATLAS_PROPRIETARY, "OPPORTUNITY_V103", None, ("SCANNER", "HOME", "RESEARCH"), "METHODOLOGY_OWNER", ATLAS),
    _entry("CONFIDENCE", ATLAS, ATLAS, (), CURRENT_PRIMARY, ATLAS_PROPRIETARY, "CONFIDENCE_V103", None, ("SCANNER", "HOME", "RESEARCH"), "METHODOLOGY_OWNER", ATLAS),
    _entry("RECOMMENDATION", ATLAS, ATLAS, (), CURRENT_PRIMARY, ATLAS_PROPRIETARY, "RECOMMENDATION_V1", None, ("SCANNER", "HOME", "RESEARCH"), "METHODOLOGY_OWNER", ATLAS),
    _entry("BUY_NOW", ATLAS, ATLAS, (), CURRENT_PRIMARY, ATLAS_PROPRIETARY, "BUY_NOW_V1", None, ("SCANNER", "HOME"), "METHODOLOGY_OWNER", ATLAS),
    _entry("RANKING", ATLAS, ATLAS, (), CURRENT_PRIMARY, ATLAS_PROPRIETARY, "RANKING_V1", None, ("SCANNER", "HOME"), "METHODOLOGY_OWNER", ATLAS),
    _entry("ATLAS_FAIR_VALUE", ATLAS, ATLAS, (), CURRENT_PRIMARY, ATLAS_PROPRIETARY, "ATLAS_FAIR_VALUE_V1", None, ("SCANNER", "HOME", "RESEARCH"), "METHODOLOGY_OWNER", ATLAS),
    _entry("DECISION_EXPECTED_RETURN", ATLAS, ATLAS, (), CURRENT_PRIMARY, ATLAS_PROPRIETARY, "DECISION_EXPECTED_RETURN_V1", None, ("SCANNER", "HOME", "RESEARCH"), "METHODOLOGY_OWNER", ATLAS),
    _entry("TRADE_PLAN", ATLAS, ATLAS, (), CURRENT_PRIMARY, ATLAS_PROPRIETARY, "TRADE_PLAN_V1052", None, ("SCANNER", "HOME", "RESEARCH"), "METHODOLOGY_OWNER", ATLAS),
    _entry("POSITION_SIZING", ATLAS, ATLAS, (), CURRENT_PRIMARY, ATLAS_PROPRIETARY, "POSITION_SIZING_V1", None, ("SCANNER", "HOME", "RESEARCH"), "METHODOLOGY_OWNER", ATLAS),
    _entry("DETERMINISTIC_INTELLIGENCE", ATLAS, ATLAS, (), CURRENT_PRIMARY, ATLAS_PROPRIETARY, "ATLAS_INTELLIGENCE_V1", None, ("SCANNER", "HOME", "RESEARCH", "ASK_ATLAS"), "METHODOLOGY_OWNER", ATLAS),
    _entry("AI_SYNTHESIS", ATLAS, ATLAS, (), CURRENT_PRIMARY, ATLAS_PROPRIETARY, "ATLAS_SYNTHESIS_V1", None, ("HOME", "RESEARCH", "ASK_ATLAS"), "REPORTING_ONLY", ATLAS),
)


# Explicit Research only. Scanner/current global authority in PROVIDER_OWNERSHIP
# is intentionally unchanged until separately replayed and approved.
EXPLICIT_RESEARCH_FMP_PRIMARY: Final[tuple[ExplicitResearchAuthority, ...]] = tuple(
    ExplicitResearchAuthority(
        family=family,
        primary=FMP,
        rollback_owner=rollback,
        authority_status=FMP_PRIMARY_YAHOO_FALLBACK,
        commercial_status=COMMERCIAL_LICENSE_PENDING,
    )
    for family, rollback in (
        ("COMPANY_PROFILE_REFERENCE", YAHOO), ("COMPANY_PEERS", FMP),
        ("FINANCIAL_STATEMENTS", YAHOO), ("KEY_METRICS", YAHOO),
        ("FINANCIAL_RATIOS", YAHOO), ("FINANCIAL_GROWTH", YAHOO),
        ("EARNINGS_HISTORY", YAHOO), ("EARNINGS_ACTUAL_VS_ESTIMATE", YAHOO),
        ("ANALYST_ESTIMATES", YAHOO), ("ANALYST_CONSENSUS", FINNHUB),
        ("ANALYST_PRICE_TARGETS", FINNHUB), ("ANALYST_FIRM_ACTIONS", FINNHUB),
        ("INSTITUTIONAL_OWNERSHIP", YAHOO), ("FUND_13F_HOLDINGS", MIXED_LEGACY),
        ("COMPANY_NEWS", NEWSAPI), ("PRESS_RELEASES", MIXED_LEGACY),
    )
)


def provider_ownership_summary() -> tuple[ProviderOwnership, ...]:
    """Return immutable governance records; never select a provider value."""
    return PROVIDER_OWNERSHIP


def provider_migration_metrics() -> dict[str, int]:
    """Return deterministic governance counts for migration reporting."""
    return {
        "total_families": len(PROVIDER_OWNERSHIP),
        "fmp_intended_primary_families": sum(
            item.intended_primary == FMP for item in PROVIDER_OWNERSHIP
        ),
        "fmp_current_primary_families": sum(
            item.current_primary == FMP for item in PROVIDER_OWNERSHIP
        ),
        "families_under_validation": sum(
            item.authority_status in {MIGRATION_VALIDATION, SHADOW_VALIDATION, READY_FOR_CUTOVER}
            for item in PROVIDER_OWNERSHIP
        ),
    }


__all__ = [
    "ATLAS", "COMMERCIAL_LICENSE_PENDING", "CURRENT_PRIMARY", "FINNHUB",
    "EXPLICIT_RESEARCH_FMP_PRIMARY", "ExplicitResearchAuthority", "FMP", "FMP_PRIMARY", "FMP_PRIMARY_YAHOO_FALLBACK",
    "LEGACY_PENDING_REMOVAL", "LICENSED_MARKET_DATA_PROVIDER",
    "MIGRATION_VALIDATION", "NEWSAPI", "PROVIDER_OWNERSHIP",
    "PROVIDER_OWNERSHIP_VERSION", "ProviderOwnership", "READY_FOR_CUTOVER",
    "SEC", "SHADOW_VALIDATION", "SUPPORTED_AUTHORITY_STATES",
    "SUPPORTED_PROVIDERS", "YAHOO", "provider_migration_metrics",
    "provider_ownership_summary",
]
