"""Lightweight presentation system for customer and internal ATLAS surfaces."""
from __future__ import annotations

import html
import re

import streamlit as st


def action_class(value: object) -> str:
    token = re.sub(r"[^a-z0-9]+", "-", str(value or "RATING_NOT_PUBLISHED").lower()).strip("-")
    return f"atlas-action atlas-action-{token or 'rating-not-published'}"


def action_badge(value: object, *, label: str | None = None) -> str:
    raw = str(value or "RATING_NOT_PUBLISHED")
    text = label or raw.replace("_", " ").title()
    return f'<span class="{action_class(raw)}"><i aria-hidden="true"></i>{html.escape(text)}</span>'


def inject_atlas_design_system() -> None:
    """Install a restrained, responsive visual system once per Streamlit run."""
    st.markdown(
        """
        <style>
        :root{--atlas-ink:#e8edf5;--atlas-ink-2:#bac5d4;--atlas-muted:#8795a8;--atlas-canvas:#09111d;--atlas-surface:#101b2a;--atlas-surface-2:#142235;--atlas-line:rgba(148,163,184,.18);--atlas-line-strong:rgba(148,163,184,.3);--atlas-brand:#76a9ea;--atlas-brand-strong:#4f8ddc;--atlas-cyan:#54c6c0;--atlas-positive:#6bc4a4;--atlas-caution:#e1b764;--atlas-negative:#e58b8b;--atlas-neutral:#a9b4c4;--atlas-radius:14px;--atlas-radius-sm:9px;--atlas-shadow:0 12px 34px rgba(0,0,0,.18);--atlas-section-gap:1.35rem;--atlas-card-pad:1rem;--atlas-page-max:1180px;--atlas-font:-apple-system,BlinkMacSystemFont,"Segoe UI",Inter,Roboto,sans-serif}
        html,body,[class*="css"]{font-family:var(--atlas-font)}.stApp{background:radial-gradient(900px 460px at 14% -15%,rgba(47,97,154,.12),transparent 66%),var(--atlas-canvas);color:var(--atlas-ink)}
        [data-testid="stHeader"]{background:rgba(9,17,29,.96)!important;border-bottom:1px solid var(--atlas-line)}[data-testid="stMainBlockContainer"]{max-width:var(--atlas-page-max);padding-top:1.15rem!important}[data-testid="stMainBlockContainer"] h1{font-size:clamp(1.85rem,3vw,2.55rem);letter-spacing:-.035em;line-height:1.08}[data-testid="stMainBlockContainer"] h2{font-size:clamp(1.3rem,2vw,1.65rem);letter-spacing:-.022em}[data-testid="stMainBlockContainer"] h3{font-size:1.08rem;letter-spacing:-.012em}[data-testid="stCaptionContainer"],small{color:var(--atlas-muted)}hr{border-color:var(--atlas-line)!important}
        [data-testid="stRadio"] [role="radiogroup"]{gap:.3rem;padding:.28rem;border:1px solid var(--atlas-line);border-radius:12px;background:rgba(16,27,42,.82)}[data-testid="stRadio"] [role="radiogroup"] label{min-height:38px;padding:.4rem .72rem!important;border-radius:8px;color:var(--atlas-ink-2);transition:background-color .12s ease,color .12s ease}[data-testid="stRadio"] [role="radiogroup"] label:has(input:checked){color:#f7fbff;background:rgba(79,141,220,.2);box-shadow:inset 0 -2px 0 var(--atlas-brand)}[data-testid="stRadio"] [role="radiogroup"] label:focus-within{outline:2px solid var(--atlas-brand);outline-offset:2px}
        [data-testid="stVerticalBlockBorderWrapper"]{border-color:var(--atlas-line)!important;border-radius:var(--atlas-radius)!important;background:linear-gradient(145deg,rgba(20,34,53,.92),rgba(13,23,37,.94));box-shadow:0 1px 0 rgba(255,255,255,.025)}[data-testid="stMetric"]{padding:.72rem .78rem;border:1px solid var(--atlas-line);border-radius:var(--atlas-radius-sm);background:rgba(9,17,29,.4)}[data-testid="stMetricLabel"]{color:var(--atlas-muted);font-size:.76rem;letter-spacing:.045em;text-transform:uppercase}[data-testid="stMetricValue"]{color:var(--atlas-ink);font-variant-numeric:tabular-nums;letter-spacing:-.025em}
        .stButton>button,[data-testid="stFormSubmitButton"]>button{min-height:40px;border-radius:9px!important;border-color:var(--atlas-line-strong)!important;font-weight:650;letter-spacing:.005em}.stButton>button[kind="primary"],[data-testid="stFormSubmitButton"]>button[kind="primary"]{background:#2868ad!important;border-color:#397dc4!important;color:#fff!important}.stTextInput input{min-height:42px;border-color:var(--atlas-line-strong)!important;border-radius:9px!important;background:rgba(9,17,29,.6)!important}[data-testid="stExpander"] details{border-color:var(--atlas-line)!important;border-radius:10px!important;background:rgba(16,27,42,.45)}[data-testid="stDataFrame"]{border:1px solid var(--atlas-line);border-radius:10px;overflow:hidden}div[data-baseweb="notification"]{border-radius:10px;border:1px solid var(--atlas-line)}
        .atlas-kicker{display:flex;align-items:center;gap:.45rem;color:var(--atlas-brand);font-size:.72rem;font-weight:750;letter-spacing:.1em;text-transform:uppercase}.atlas-kicker:before{content:"";width:18px;height:2px;border-radius:2px;background:var(--atlas-brand)}.atlas-certification-chip,.atlas-source-chip{display:inline-flex;align-items:center;gap:.32rem;padding:.26rem .52rem;border:1px solid var(--atlas-line);border-radius:999px;color:var(--atlas-ink-2);background:rgba(20,34,53,.7);font-size:.72rem;font-weight:650}.atlas-certification-chip:before{content:"✓";color:var(--atlas-positive)}.atlas-source-chips{display:flex;flex-wrap:wrap;gap:.38rem;margin:.7rem 0}.atlas-empty-state{padding:1rem 1.05rem;border:1px dashed var(--atlas-line-strong);border-radius:var(--atlas-radius);background:rgba(16,27,42,.48)}.atlas-empty-state strong{display:block;margin-bottom:.2rem;color:var(--atlas-ink)}.atlas-empty-state span{color:var(--atlas-muted);font-size:.88rem}
        .atlas-action{display:inline-flex;align-items:center;gap:.42rem;width:max-content;max-width:100%;padding:.32rem .58rem;border:1px solid currentColor;border-radius:999px;font-size:.72rem;font-weight:780;line-height:1;letter-spacing:.055em;text-transform:uppercase;white-space:nowrap}.atlas-action i{width:.46rem;height:.46rem;border-radius:50%;background:currentColor;box-shadow:0 0 0 3px color-mix(in srgb,currentColor 18%,transparent)}.atlas-action-buy-now{color:#7ad2b0;background:rgba(39,120,89,.12)}.atlas-action-build-a-position{color:#84b6ef;background:rgba(49,103,166,.14)}.atlas-action-wait-for-better-entry,.atlas-action-wait-for-confirmation,.atlas-action-watch-not-ready{color:#e5bd73;background:rgba(137,94,25,.13)}.atlas-action-avoid{color:#eda1a1;background:rgba(143,56,56,.13)}.atlas-action-rating-not-published{color:#b1bbc9;background:rgba(92,103,119,.13)}
        body:has([data-atlas-qa="home-guidance-vnext"]) .atlas-home-guidance-hero{border-bottom:1px solid var(--atlas-line);padding-bottom:.8rem}body:has([data-atlas-qa="home-guidance-vnext"]) .atlas-home-guidance-hero small{display:inline-flex;margin-top:.35rem;padding:.24rem .45rem;border-radius:999px;background:rgba(52,104,164,.12);color:#a9caef}body:has([data-atlas-qa="research-vnext"]) [data-testid="stMainBlockContainer"],body:has([data-atlas-qa="research-report-vnext"]) [data-testid="stMainBlockContainer"]{max-width:1100px}body:has([data-atlas-qa="ask-atlas-vnext"]) [data-testid="stForm"]{padding:1rem;border:1px solid var(--atlas-line);border-radius:var(--atlas-radius);background:rgba(16,27,42,.72)}body:has([data-atlas-qa="ask-atlas-vnext"]) [data-testid="stMarkdownContainer"] blockquote{border-left:3px solid var(--atlas-brand);background:rgba(20,34,53,.56);border-radius:0 10px 10px 0;padding:.75rem 1rem}body:has([data-atlas-qa="watchlist-vnext"]) [data-testid="stVerticalBlockBorderWrapper"]:has(.atlas-watchlist-card-anchor){border-left:3px solid var(--atlas-brand)!important}body:has([data-atlas-qa="internal-report-card"]) [data-testid="stMetric"]{min-height:94px}.atlas-report-card-hero{padding:.95rem 1rem;margin:.15rem 0 1rem;border:1px solid var(--atlas-line);border-radius:var(--atlas-radius);background:linear-gradient(120deg,rgba(31,67,106,.24),rgba(16,27,42,.8))}.atlas-report-card-hero h1{margin:.15rem 0!important}.atlas-report-card-hero p{margin:.2rem 0 0;color:var(--atlas-ink-2)}
        @media(max-width:700px){:root{--atlas-card-pad:.72rem;--atlas-section-gap:1rem}[data-testid="stMainBlockContainer"]{padding:.45rem .72rem 5.5rem!important;max-width:100vw;overflow-x:hidden}[data-testid="stRadio"] [role="radiogroup"]{flex-wrap:nowrap!important;overflow-x:auto!important;scrollbar-width:none;border-radius:10px}[data-testid="stRadio"] [role="radiogroup"] label{flex:0 0 auto;min-height:42px;padding:.42rem .62rem!important;white-space:nowrap}[data-testid="stHorizontalBlock"]{gap:.42rem!important}[data-testid="stMetric"]{padding:.58rem .62rem;min-width:0}[data-testid="stMetricLabel"] p{font-size:.69rem!important;line-height:1.2!important;white-space:normal}[data-testid="stMetricValue"]{font-size:1.08rem!important;overflow-wrap:anywhere}[data-testid="stDataFrame"]{max-width:calc(100vw - 1.44rem)}.atlas-source-chips{gap:.3rem}.atlas-source-chip{font-size:.68rem}.atlas-action{white-space:normal;line-height:1.18}}
        @media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important;animation:none!important}}
        </style>
        <span data-atlas-qa="atlas-design-system" data-atlas-design-version="1" aria-hidden="true" style="display:none">atlas-design-system</span>
        """,
        unsafe_allow_html=True,
    )


__all__ = ["action_badge", "action_class", "inject_atlas_design_system"]
