"""
Atlas V105 — Institutional Research Report UI

This module renders the complete premium research report generated by
engines/research_engine_v105.py.
"""

from __future__ import annotations

from html import escape
from typing import Any, Mapping

import pandas as pd
import streamlit as st

from engines.research_engine_v105 import build_institutional_research


def _money(value: Any) -> str:
    try:
        return f"${float(value):,.2f}"
    except (TypeError, ValueError):
        return "Under review"


def _percent(value: Any, signed: bool = False) -> str:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return "Under review"
    sign = "+" if signed and number > 0 else ""
    return f"{sign}{number:.1f}%"


def _score(value: Any) -> str:
    try:
        return f"{float(value):.1f}"
    except (TypeError, ValueError):
        return "Under review"


def _verdict(value: Any) -> str:
    return str(value or "MONITOR").replace("_", " ").title()


def inject_v105_css() -> None:
    st.markdown(
        """
        <style>
        .atlas-v105-hero {
            border-radius: 24px;
            padding: 26px;
            border: 1px solid rgba(95, 159, 226, 0.32);
            background:
                radial-gradient(circle at top right,
                    rgba(43, 128, 213, 0.18), transparent 38%),
                linear-gradient(145deg,
                    rgba(14, 39, 65, 0.98),
                    rgba(7, 18, 34, 0.98));
            margin-bottom: 18px;
        }
        .atlas-v105-kicker {
            color: #8fa8c4;
            font-size: 0.75rem;
            font-weight: 850;
            letter-spacing: 0.14em;
            text-transform: uppercase;
        }
        .atlas-v105-title {
            color: #f8faff;
            font-size: 2.5rem;
            font-weight: 900;
            line-height: 1;
            margin-top: 8px;
        }
        .atlas-v105-subtitle {
            color: #aebbd0;
            font-size: 1rem;
            margin-top: 9px;
        }
        .atlas-v105-summary {
            border-left: 4px solid #4ea4f2;
            border-radius: 12px;
            padding: 15px 17px;
            background: rgba(13, 35, 59, 0.62);
            color: #dce4ef;
            line-height: 1.62;
            margin: 8px 0 18px 0;
        }
        .atlas-v105-section-note {
            color: #97a6ba;
            font-size: 0.88rem;
            margin-top: -8px;
            margin-bottom: 12px;
        }
        </style>
        """,
        unsafe_allow_html=True,
    )


def _render_scorecard(report: Mapping[str, Any]) -> None:
    scorecard = report.get("component_scorecard") or {}

    visible = [
        (name, value)
        for name, value in scorecard.items()
        if value is not None
    ]

    if not visible:
        st.info("No component-level scorecard is available.")
        return

    for name, value in visible:
        try:
            numeric = max(0.0, min(100.0, float(value)))
        except (TypeError, ValueError):
            continue

        st.progress(
            numeric / 100.0,
            text=(
                f"{name.replace('_', ' ').title()}: "
                f"{numeric:.1f}"
            ),
        )


def _render_fair_value(report: Mapping[str, Any]) -> None:
    cases = report.get("fair_value_cases") or []

    columns = st.columns(3)

    for column, case in zip(columns, cases):
        with column:
            label = str(case.get("label") or "Case")
            st.markdown(f"### {label} Case")
            st.metric(
                "Fair Value",
                _money(case.get("fair_value")),
            )
            st.metric(
                "Expected Return",
                _percent(
                    case.get("expected_return_pct"),
                    signed=True,
                ),
            )
            st.caption(
                f"Probability: "
                f"{_percent(case.get('probability_pct'))}"
            )


def _render_checklist(report: Mapping[str, Any]) -> None:
    checklist = report.get("buy_checklist") or []

    for item in checklist:
        status = item.get("status")
        label = item.get("label")
        value = item.get("value")

        text = (
            f"{label}: {_score(value)} "
            f"(threshold {_score(item.get('threshold'))})"
        )

        if status == "Passed":
            st.success(text, icon="✓")
        elif status == "Missing":
            st.info(text, icon="—")
        else:
            st.warning(text, icon="!")


def render_v105_research_report(
    row: Mapping[str, Any],
) -> None:
    inject_v105_css()

    report = build_institutional_research(row)

    st.markdown(
        f"""
        <div class="atlas-v105-hero">
          <div class="atlas-v105-kicker">Atlas V105 Institutional Research</div>
          <div class="atlas-v105-title">{escape(str(report.get("ticker") or "UNKNOWN"))}</div>
          <div class="atlas-v105-subtitle">
            {escape(str(report.get("company") or ""))}
            · {escape(str(report.get("sector") or "Unknown"))}
            · {_verdict(report.get("committee_verdict"))}
          </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    m1, m2, m3, m4 = st.columns(4)
    m1.metric(
        "Committee Verdict",
        _verdict(report.get("committee_verdict")),
    )
    m2.metric(
        "Opportunity",
        _score(report.get("opportunity_score")),
    )
    m3.metric(
        "Confidence",
        _percent(report.get("confidence_pct")),
    )
    m4.metric(
        "Suggested Position",
        report.get("position_size_range"),
    )

    m5, m6, m7, m8 = st.columns(4)
    m5.metric(
        "Current Price",
        _money(report.get("current_price")),
    )
    m6.metric(
        "Validated Fair Value",
        _money(report.get("validated_fair_value")),
    )
    m7.metric(
        "Expected Return",
        _percent(
            report.get("expected_return_pct"),
            signed=True,
        ),
    )
    m8.metric(
        "Primary Blocker",
        report.get("primary_blocker"),
    )

    st.markdown("## Executive Summary")
    st.markdown(
        f"""
        <div class="atlas-v105-summary">
          {escape(str(report.get("executive_summary") or ""))}
        </div>
        """,
        unsafe_allow_html=True,
    )

    tabs = st.tabs(
        [
            "Investment Thesis",
            "Earnings & Transcript",
            "Wall Street",
            "Ownership & Political",
            "Fair Value",
            "Risk",
            "Buy Checklist",
        ]
    )

    with tabs[0]:
        st.markdown("### Investment Thesis")
        st.write(report.get("investment_thesis"))

        bull, bear = st.columns(2)

        with bull:
            st.markdown("### Bull Case")
            items = report.get("bull_case") or []
            if items:
                for item in items:
                    st.success(str(item), icon="✓")
            else:
                st.info("No structured bull-case drivers are available.")

        with bear:
            st.markdown("### Bear Case")
            items = report.get("bear_case") or []
            if items:
                for item in items:
                    st.warning(str(item), icon="!")
            else:
                st.info("No structured bear-case items are available.")

        st.markdown("### Institutional Scorecard")
        _render_scorecard(report)

    with tabs[1]:
        earnings = report.get("earnings_intelligence") or {}

        e1, e2, e3, e4 = st.columns(4)
        e1.metric(
            "EPS Surprise",
            _percent(
                earnings.get("eps_surprise_pct"),
                signed=True,
            ),
        )
        e2.metric(
            "Revenue Surprise",
            _percent(
                earnings.get("revenue_surprise_pct"),
                signed=True,
            ),
        )
        e3.metric(
            "Atlas Interpretation",
            earnings.get("interpretation"),
        )
        e4.metric(
            "Confidence Impact",
            f"{_score(earnings.get('confidence_impact_points'))} pts",
        )

        st.markdown("### Guidance")
        st.write(earnings.get("guidance"))

        st.markdown("### Transcript Summary")
        st.write(earnings.get("transcript_summary"))

    with tabs[2]:
        wall_street = report.get("wall_street") or {}

        w1, w2, w3 = st.columns(3)
        w1.metric(
            "Buy Ratings",
            wall_street.get("buy_count")
            if wall_street.get("buy_count") is not None
            else "Under review",
        )
        w2.metric(
            "Hold Ratings",
            wall_street.get("hold_count")
            if wall_street.get("hold_count") is not None
            else "Under review",
        )
        w3.metric(
            "Sell Ratings",
            wall_street.get("sell_count")
            if wall_street.get("sell_count") is not None
            else "Under review",
        )

        t1, t2, t3 = st.columns(3)
        t1.metric(
            "Average Target",
            _money(wall_street.get("average_target")),
        )
        t2.metric(
            "High Target",
            _money(wall_street.get("high_target")),
        )
        t3.metric(
            "Low Target",
            _money(wall_street.get("low_target")),
        )

        st.info(wall_street.get("atlas_alignment"))

    with tabs[3]:
        o1, o2, o3 = st.columns(3)
        o1.metric(
            "Institutional Support",
            _score(report.get("institutional_score")),
        )
        o2.metric(
            "Insider Support",
            _score(report.get("insider_score")),
        )
        o3.metric(
            "Political Support",
            _score(report.get("political_score")),
        )

        st.caption(
            "These scores use only evidence included in the current "
            "saved scan. Missing values remain explicitly under review."
        )

    with tabs[4]:
        st.markdown("### Probability-Weighted Fair Value")
        _render_fair_value(report)

    with tabs[5]:
        matrix = report.get("risk_matrix") or []

        st.dataframe(
            pd.DataFrame(matrix),
            hide_index=True,
            use_container_width=True,
            column_config={
                "category": "Risk Category",
                "support_score": st.column_config.NumberColumn(
                    "Support Score",
                    format="%.1f",
                ),
                "risk_level": "Risk Level",
            },
        )

    with tabs[6]:
        st.markdown("### Institutional Buy Checklist")
        _render_checklist(report)


__all__ = [
    "inject_v105_css",
    "render_v105_research_report",
]
